//
//  FormField.swift
//
//  Model for custom form fields in tenant formSchema.
//

import Foundation

struct FormField: Identifiable, Equatable {
    var id: String
    var key: String
    var label: String
    var type: FormFieldType
    var required: Bool
    var options: [String]?
    var placeholder: String?

    init(
        id: String = UUID().uuidString,
        key: String,
        label: String,
        type: FormFieldType = .text,
        required: Bool = true,
        options: [String]? = nil,
        placeholder: String? = nil
    ) {
        self.id = id
        self.key = key
        self.label = label
        self.type = type
        self.required = required
        self.options = options
        self.placeholder = placeholder
    }

    func toFirestore() -> [String: Any] {
        var dict: [String: Any] = ["key": key, "label": label, "type": type.rawValue, "required": required]
        if let options { dict["options"] = options }
        if let placeholder { dict["placeholder"] = placeholder }
        return dict
    }

    static func fromFirestore(_ dict: [String: Any]) -> FormField? {
        guard let key = dict["key"] as? String, let label = dict["label"] as? String else { return nil }
        let typeRaw = dict["type"] as? String ?? "text"
        let type = FormFieldType(rawValue: typeRaw) ?? .text
        let required = dict["required"] as? Bool ?? true
        let options = dict["options"] as? [String]
        let placeholder = dict["placeholder"] as? String
        return FormField(
            id: key,
            key: key,
            label: label,
            type: type,
            required: required,
            options: options,
            placeholder: placeholder
        )
    }
}

enum FormFieldType: String, CaseIterable {
    case text
    case email
    case phone
    case textarea
    case file
    case select

    var displayName: String {
        switch self {
        case .text: return "Text"
        case .email: return "Email"
        case .phone: return "Phone"
        case .textarea: return "Long text"
        case .file: return "File / photos"
        case .select: return "Dropdown"
        }
    }
}

/// Guided `/book` wizard buckets — matches web `guidedWizardBucketForField`.
enum GuidedFormStep: String, CaseIterable, Identifiable {
    case service
    case project
    case contact

    var id: String { rawValue }

    var stepNumber: Int {
        switch self {
        case .service: return 1
        case .project: return 2
        case .contact: return 3
        }
    }

    var defaultTitle: String {
        switch self {
        case .service: return "Service"
        case .project: return "Project details"
        case .contact: return "About you"
        }
    }

    static func forField(_ field: FormField) -> GuidedFormStep {
        let key = field.key.lowercased()
        if key == "service" { return .service }
        if key == "name" || key == "email" || key == "phone" { return .contact }
        return .project
    }

    static func contactSortOrder(for key: String) -> Int {
        switch key.lowercased() {
        case "name": return 0
        case "email": return 1
        case "phone": return 2
        default: return 99
        }
    }

    static func parseOrder(from stored: [String]?) -> [GuidedFormStep] {
        guard let stored, !stored.isEmpty else { return allCases }
        var ordered = stored.compactMap { GuidedFormStep(rawValue: $0) }
        for step in allCases where !ordered.contains(step) {
            ordered.append(step)
        }
        return ordered
    }
}

extension FormField {
    var guidedStep: GuidedFormStep {
        GuidedFormStep.forField(self)
    }

    /// Subtitle for Manage → Form fields list rows.
    var listSubtitle: String {
        if type == .select, let count = options?.count, count > 0 {
            return "Dropdown · \(count) options"
        }
        return type.displayName
    }

    /// New fields use `field_<n>` until the owner sets a real label/key.
    var usesAutoGeneratedKey: Bool {
        key.range(of: #"^field_\d+$"#, options: .regularExpression) != nil
    }
}
